version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
       MYSQL_DATABASE: 'altYapiDatabase'
       MYSQL_ROOT_PASSWORD: 'test123'
    volumes:
      - app-data:/var/lib/mysql

volumes:
  app-data:
